### ISSUE TITLE
edit profile page text fields icon

### ISSUE THREAD

**Issue by renjithraj2005** [sayonetech/eatio#55]

**Comment by shebink** [comment]
@rahulsayone see the attached icons for gender, location and age. 

![age](https://cloud.githubusercontent.com/assets/5989093/7915270/1272173a-089a-11e5-9b14-99fea31348c7.png)
![gender](https://cloud.githubusercontent.com/assets/5989093/7915271/12726050-089a-11e5-97d2-61dc9a3b6369.png)
![location](https://cloud.githubusercontent.com/assets/5989093/7915272/127d267a-089a-11e5-918e-73fa18838f2a.png)
